#!/usr/bin/env python3
"""Verify HuAIBench artifact counts used by the paper.

The script avoids model/API calls. It checks that the released files needed for
the scorecard exist and recomputes the core counts from CSV/JSONL records.
"""

from __future__ import annotations

import csv
import hashlib
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_JSON = ROOT / "analysis" / "artifact_audit_summary.json"
OUT_TEX = ROOT / "analysis" / "artifact_audit_summary.tex"


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def count_jsonl(path: Path) -> int:
    if not path.exists():
        return 0
    with path.open(encoding="utf-8") as f:
        return sum(1 for line in f if line.strip())


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def load_manifest(path: Path) -> tuple[int, int]:
    checked = 0
    mismatches = 0
    with path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            expected, rel = line.split(maxsplit=1)
            target = ROOT / rel
            checked += 1
            if not target.exists() or sha256(target) != expected:
                mismatches += 1
    return checked, mismatches


def main() -> None:
    manifest_rows = read_csv(ROOT / "data" / "manifest.csv")
    full = read_csv(ROOT / "data" / "classifications" / "full.csv")
    gold1 = read_csv(ROOT / "data" / "classifications" / "gold_human1.csv")
    gold2 = read_csv(ROOT / "data" / "classifications" / "gold_human2.csv")
    root_labels = read_csv(ROOT / "analysis" / "root_cause_human_audit" / "label.csv")

    by_source = Counter(row["model"] for row in full)
    by_stage = Counter((row["model"], row["stage"]) for row in full)
    zero_shot = [row for row in full if row["stage"] == "zero_shot"]
    reflect = [row for row in full if row["stage"] == "reflect"]
    problems = {row["problem_id"] for row in full}

    ai_zero = Counter()
    ai_correct = Counter()
    for pid in problems:
        for model in ("gpt-3.5-turbo-0125", "gpt-5.4-nano"):
            ai_zero[model] += count_jsonl(ROOT / "data" / "problems" / pid / "ai" / model / "incorrect.jsonl")
            ai_correct[model] += count_jsonl(ROOT / "data" / "problems" / pid / "ai" / model / "correct.jsonl")

    manifest_files, manifest_mismatches = load_manifest(ROOT / "ARTIFACT_MANIFEST.sha256")

    result = {
        "manifest_files": manifest_files,
        "manifest_mismatches": manifest_mismatches,
        "problems": len(problems),
        "manifest_problem_rows": len(manifest_rows),
        "full_rows": len(full),
        "zero_shot_rows": len(zero_shot),
        "reflect_rows": len(reflect),
        "source_rows": dict(by_source),
        "stage_rows": {f"{k[0]}:{k[1]}": v for k, v in by_stage.items()},
        "gold_human1_rows": len(gold1),
        "gold_human2_rows": len(gold2),
        "root_cause_rows": len(root_labels),
        "ai_zero_shot_incorrect_jsonl": dict(ai_zero),
        "ai_zero_shot_correct_jsonl": dict(ai_correct),
    }
    OUT_JSON.write_text(json.dumps(result, indent=2), encoding="utf-8")

    lines = [
        "% Auto-generated by analysis/artifact_audit.py",
        f"\\newcommand{{\\ArtifactManifestFiles}}{{{manifest_files}}}",
        f"\\newcommand{{\\ArtifactManifestMismatches}}{{{manifest_mismatches}}}",
        f"\\newcommand{{\\ArtifactProblems}}{{{len(problems)}}}",
        f"\\newcommand{{\\ArtifactFullRows}}{{{len(full)}}}",
        f"\\newcommand{{\\ArtifactGoldRows}}{{{len(gold1)}}}",
        f"\\newcommand{{\\ArtifactRootRows}}{{{len(root_labels)}}}",
    ]
    OUT_TEX.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
